Repository team-ecolink/ecolink-frontend, pull requests merged in 2024-01, with the labels that each got.

#4 Feat: 더미 홈페이지 생성
  .eslintrc.json
  package-lock.json
  package.json
  public/assets/ecolink.png
  src/App.tsx
  src/components/Navigationbar.tsx
  src/components/index.ts
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/Mypage.tsx
  src/pages/Search.tsx
  src/pages/index.ts
Labels: new feature

#12 Feature/11 globalStyle 적용
  src/App.tsx
  src/GlobalStyle.tsx
Labels: new feature

#13 Feature/8 내비게이션 바 제작 / 1 로그인 페이지 제작
  package-lock.json
  public/assets/Login/kakao_login_button.png
  public/assets/Login/login_logo.png
  public/assets/Login/login_text.png
  public/assets/Login/naver_login_button.png
  public/assets/Navbar/backbutton.png
  public/assets/Navbar/home_mobile.png
  public/assets/Navbar/logo.png
  public/assets/Navbar/map_mobile.png
  public/assets/Navbar/search_mobile.png
  public/assets/Navbar/searchimg.png
  public/assets/Navbar/settingimg.png
  public/assets/Navbar/user_mobile.png
  public/assets/Navbar/userimg.png
  public/assets/ecolink.png
  public/index.html
  src/App.tsx
  src/components/Login/Loginbutton.tsx
  src/components/Mobiletop.tsx
  src/components/Navigationbar.tsx
  src/components/index.ts
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/Login/KakaoLoginHandeler.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/NaverLoginHandeler.tsx
  src/pages/index.ts
Labels: new feature

#10 Feature/5 mypage 생성
  package-lock.json
  package.json
  public/assets/MyPage/bookmark.png
  public/assets/MyPage/close.png
  public/assets/MyPage/favorite.png
  public/assets/MyPage/kakao.png
  public/assets/MyPage/lightgray.png
  public/assets/MyPage/settings.png
  public/assets/MyPage/trash.png
  public/assets/MyPage/white.png
  src/App.tsx
  src/components/Modal/ConfirmModal.tsx
  src/components/Modal/scroll.ts
  src/components/Mypage/BookMarkList.tsx
  src/components/Mypage/Dummy/BookMarkDummy.ts
  src/components/Mypage/Dummy/ReviewDummy.ts
  src/components/Mypage/PersonalInfo.tsx
  src/components/Mypage/ReviewList.tsx
  src/components/Mypage/StoreOwner.tsx
  src/components/Mypage/index.ts
  src/pages/Mypage.tsx
  src/pages/Owner.tsx
  src/pages/Setting.tsx
  src/pages/index.ts
  src/recoil/confirmModal.ts
  src/recoil/index.ts
Labels: new feature

#18 Feature/14 점주신청페이지
  package-lock.json
  package.json
  src/App.tsx
  src/components/Owner/InputField.tsx
  src/components/Owner/SearchAddress.tsx
  src/components/Owner/index.ts
  src/hooks/Owner/index.ts
  src/hooks/Owner/useInput.ts
  src/pages/Owner.tsx
  src/pages/index.ts
  src/recoil/Owner/owner.ts
  src/recoil/Owner/ownerTypes.ts
  src/recoil/index.ts
Labels: new feature

#24 Feature/2 검색 페이지 제작 1
  public/assets/Search/delete.png
  public/assets/Search/logo.png
  public/assets/Search/search.png
  src/components/Search/PopularSearchList.tsx
  src/components/Search/RecentSearchList.tsx
  src/components/Search/SearchBar.tsx
  src/components/Search/SearchToggle.tsx
  src/pages/Search.tsx
  src/recoil/index.ts
  src/recoil/searchToggleState.ts
Labels: new feature

#22 Feature/15 리뷰 작성 페이지 제작
  public/assets/StoreDetail/new_pic.png
  public/assets/StoreDetail/star_empty.png
  public/assets/StoreDetail/star_full.png
  public/assets/StoreDetail/xbutton.png
  src/App.tsx
  src/GlobalStyle.tsx
  src/components/Example.tsx
  src/components/Navigationbar.tsx
  src/components/ReviewWrite/Addpic.tsx
  src/components/ReviewWrite/ReviewWrite.tsx
  src/components/ReviewWrite/StarRating.tsx
  src/components/ReviewWrite/Storetag.tsx
  src/components/ReviewWrite/Tagitem.tsx
  src/components/ReviewWrite/TextReview.tsx
  src/components/ReviewWrite/index.ts
  src/components/index.ts
  src/pages/StoreDetail.tsx
  src/pages/index.ts
  src/recoil/index.ts
  src/recoil/reviewwritemodal.ts
Labels: new feature

#25 Feature/23 feature 매장 상세페이지 제작
  package-lock.json
  package.json
  public/assets/StoreDetail/arrow.svg
  public/assets/StoreDetail/bookmark.png
  public/assets/StoreDetail/bookmark_x.png
  public/assets/StoreDetail/call.svg
  public/assets/StoreDetail/example_pic.png
  public/assets/StoreDetail/like.svg
  public/assets/StoreDetail/location.svg
  public/assets/StoreDetail/not_like.svg
  public/assets/StoreDetail/share.svg
  public/assets/StoreDetail/star.svg
  public/assets/StoreDetail/star_empty.svg
  public/assets/StoreDetail/star_full.svg
  public/assets/StoreDetail/storefront.svg
  src/components/Mobiletop.tsx
  src/components/Mypage/BookMarkList.tsx
  src/components/ReviewWrite/ReviewWrite.tsx
  src/components/ReviewWrite/StarRating.tsx
  src/components/StoreDetail/DetailBox.tsx
  src/components/StoreDetail/Event.tsx
  src/components/StoreDetail/Eventlist.tsx
  src/components/StoreDetail/Linkbuttons.tsx
  src/components/StoreDetail/MyReview.tsx
  src/components/StoreDetail/Product.tsx
  src/components/StoreDetail/Productlist.tsx
  src/components/StoreDetail/Review.tsx
  src/components/StoreDetail/Reviewlist.tsx
  src/components/StoreDetail/SlideBox.tsx
  src/components/StoreDetail/SlidePic.tsx
  src/components/StoreDetail/StoreIndex.tsx
  src/components/StoreDetail/Storename.tsx
  src/components/StoreDetail/index.ts
  src/pages/StoreDetail.tsx
  src/pages/index.ts
  src/recoil/Reviewlist.ts
  src/recoil/index.ts
  src/recoil/types.ts
Labels: new feature

#21 Fix/20 로고 및 사이트명 수정
  package.json
  public/favicon.ico
  public/index.html
  src/components/Navigationbar.tsx
Labels: fix

#29 Update README.md
  README.md
Labels: documentation

#28 fix/ 26 네비게이션바 수정
  public/assets/Navbar/backbutton.png
  public/assets/Navbar/backbutton.svg
  public/assets/Navbar/home_mobile.png
  public/assets/Navbar/map_mobile.png
  public/assets/Navbar/search_mobile.png
  public/assets/Navbar/searchimg.svg
  public/assets/Navbar/user_mobile.png
  public/assets/Navbar/userimg.svg
  src/assets/Navbar/home_mobile.svg
  src/assets/Navbar/map_mobile.svg
  src/assets/Navbar/search_mobile.svg
  src/assets/Navbar/user_mobile.svg
  src/assets/custom.d.ts
  src/components/Mobiletop.tsx
  src/components/Navigationbar.tsx
Labels: fix

#30 fix/26 로그인 페이지 수정
  public/assets/Login/kakao.svg
  public/assets/Login/kakao_login_button.png
  public/assets/Login/line.svg
  public/assets/Login/login_logo.png
  public/assets/Login/login_text.png
  public/assets/Login/naver.svg
  public/assets/Login/naver_login_button.png
  src/components/Login/Loginbutton.tsx
Labels: fix

#35 Feature/31 판매중인 제품 더보기 페이지 제작
  src/App.tsx
  src/components/ScrollToTop.ts
  src/components/SellingProduct/DefaultList.tsx
  src/components/SellingProduct/Product.tsx
  src/components/SellingProduct/SearchBar.tsx
  src/components/SellingProduct/SlideBox.tsx
  src/components/SellingProduct/SlidePic.tsx
  src/components/SellingProduct/index.ts
  src/components/StoreDetail/Productlist.tsx
  src/components/index.ts
  src/pages/SellingProduct.tsx
  src/pages/index.ts
  src/recoil/index.ts
  src/recoil/searchToggleState.ts
Labels: new feature
