Repository team-ecolink/ecolink-frontend, pull requests merged in 2024-02, with the labels that each got.

#43 Feature/37 홈화면 페이지 제작
  public/assets/Home/arrow.svg
  public/assets/Home/star.svg
  public/assets/Home/뒤로가기.svg
  public/assets/Home/부리1.jpeg
  public/assets/Home/부리2.jpeg
  public/assets/Home/부리3.jpeg
  src/assets/Home/arrow.svg
  src/components/Example.tsx
  src/components/Home/Ad/Slider/AdSlider.tsx
  src/components/Home/Ad/Slider/SliderItem.tsx
  src/components/Home/Contents/HomeContents.tsx
  src/components/Home/Contents/Items.tsx
  src/components/Home/Contents/StoreInfo.tsx
  src/components/Home/Dummy/AdDummy.ts
  src/components/Home/Dummy/ItemDummy.ts
  src/components/Home/Dummy/StoreDummy.ts
  src/components/Home/HomeTap.tsx
  src/components/Home/index.ts
  src/components/index.ts
  src/pages/Home.tsx
Labels: new feature

#41 Feature/33 계정관리 페이지 제작
  package-lock.json
  package.json
  public/assets/Edit/close.svg
  public/assets/Edit/edit.svg
  public/assets/Edit/kakao.svg
  public/assets/Edit/plus.svg
  public/assets/Edit/profile.png
  src/App.tsx
  src/components/Edit/AccountButton.tsx
  src/components/Edit/AccountModal.tsx
  src/components/Edit/EditButton.tsx
  src/components/Edit/KakaoEmail.tsx
  src/components/Edit/NickNameEdit.tsx
  src/components/Edit/PinchZoom.tsx
  src/components/Edit/ProfileEdit.tsx
  src/components/Edit/ProfileImgModal.tsx
  src/pages/NickName.tsx
  src/pages/Setting.tsx
  src/pages/index.ts
  src/recoil/editState.ts
  src/recoil/index.ts
Labels: new feature

#42 Feature/39 매장 상세 페이지 팝업 제작
  public/assets/DetailPopup/barcode_scanner.svg
  public/assets/DetailPopup/calendar_month.svg
  public/assets/DetailPopup/call.svg
  public/assets/DetailPopup/image 20.jpg
  public/assets/DetailPopup/link.svg
  public/assets/DetailPopup/local_parking.svg
  public/assets/DetailPopup/location_on.svg
  public/assets/DetailPopup/no_stroller.svg
  public/assets/DetailPopup/pets.svg
  public/assets/DetailPopup/simple-icons_kakaotalk.svg
  public/assets/DetailPopup/valve.svg
  src/components/DetailPopup/DetailPopup.tsx
  src/components/DetailPopup/SharePopup.tsx
  src/components/StoreDetail/Linkbuttons.tsx
  src/components/StoreDetail/Storename.tsx
  src/pages/StoreDetail.tsx
  src/recoil/detailPopupModal.ts
  src/recoil/index.ts
  src/recoil/sharepopupModal.ts
Labels: new feature

#48 Feature/36 로그인 기능 구현
  src/App.tsx
  src/components/Navigationbar.tsx
  src/pages/Login/KakaoLoginHandeler.tsx
  src/pages/Login/NaverLoginHandeler.tsx
  src/pages/index.ts
  src/recoil/index.ts
  src/recoil/types.ts
  src/recoil/userInfo.ts
Labels: new feature

#54 refactor : 마우스 스크롤 제거 & 페이지 이동으로 리펙토링
  src/components/Mypage/BookMarkList.tsx
  src/components/Mypage/ReviewList.tsx
  src/pages/OwnerMypage.tsx
Labels: refactor

#61 Feature/53 이벤트 상세 팝업 제작
  public/assets/EventDetail/edit.svg
  public/assets/StoreDetail/star_empty.png
  public/assets/StoreDetail/star_full.png
  src/components/EventDetail/EventDetail.tsx
  src/components/EventDetail/SlideBox.tsx
  src/components/EventDetail/SlidePic.tsx
  src/components/EventDetail/index.ts
  src/components/EventEdit/Product.tsx
  src/components/StoreDetail/Event.tsx
  src/components/index.ts
  src/pages/Evnentmanage.tsx
  src/pages/StoreDetail.tsx
  src/recoil/eventDetail.ts
  src/recoil/index.ts
Labels: new feature

#63 Feature/57 마이페이지 정보 api 연동
  src/apis/Mypage/PersonalInfoApi.ts
  src/apis/customApi.ts
  src/components/Mypage/BookMarkList.tsx
  src/components/Mypage/PersonalInfo.tsx
  src/components/Mypage/ReviewList.tsx
  src/index.tsx
  src/pages/Mypage.tsx
  src/pages/OwnerMypage.tsx
  src/recoil/Mypage/myPageState.ts
  src/recoil/Mypage/myPageStateTypes.ts
Labels: new feature

#64 Fix/62 내비게이션 바 로그인 페이지 매장 상세 페이지 리뷰 작성 모달 수정
  public/assets/StoreDetail/LeftStroke.svg
  public/assets/StoreDetail/RightStroke.svg
  public/assets/StoreDetail/bookmark.png
  public/assets/StoreDetail/bookmark_o.svg
  public/assets/StoreDetail/bookmark_x.png
  public/assets/StoreDetail/bookmark_x.svg
  public/assets/StoreDetail/new_pic.png
  public/assets/StoreDetail/new_pic.svg
  src/App.tsx
  src/components/DetailPopup/DetailPopup.tsx
  src/components/DetailPopup/SharePopup.tsx
  src/components/Edit/AccountModal.tsx
  src/components/Edit/ProfileImgModal.tsx
  src/components/EventEdit/EventEdit.tsx
  src/components/Login/Loginbutton.tsx
  src/components/Modal/ConfirmModal.tsx
  src/components/Navigationbar.tsx
  src/components/ProductRegister/ProductRegistration.tsx
  src/components/ReviewWrite/Addpic.tsx
  src/components/ReviewWrite/ReviewWrite.tsx
  src/components/ReviewWrite/Tagitem.tsx
  src/components/ReviewWrite/Text.tsx
  src/components/StoreDetail/MyReview.tsx
  src/components/StoreDetail/Review.tsx
  src/components/StoreDetail/Reviewlist.tsx
  src/components/StoreDetail/Storename.tsx
  src/pages/StoreDetail.tsx
Labels: fix

#67 Fix/66 홈화면 tap 컴포넌트 제거 / 로그인상태 체크 함수 추가
  src/components/Home/Contents/HomeContents.tsx
  src/components/Home/HomeTap.tsx
  src/components/Home/Items.tsx
  src/components/Home/StoreInfo.tsx
  src/components/Home/index.ts
  src/pages/Home.tsx
  src/utils/isLogin.tsx
Labels: fix

#68 Feature/60 내가 쓴 리뷰 제작
  public/assets/ReviewList/heart.svg
  public/assets/ReviewList/trash.svg
  src/App.tsx
  src/components/Mypage/ReviewList.tsx
  src/pages/MyReview.tsx
  src/pages/index.ts
Labels: new feature

#74 Feature/69 매장상세페이지리뷰작성모달 api 연결
  src/App.tsx
  src/apis/StoreDetail/Bookmark.ts
  src/apis/StoreDetail/GetTags.ts
  src/apis/StoreDetail/ReviewSend.ts
  src/apis/StoreDetail/Stores.ts
  src/apis/StoreDetail/StoresEvent.ts
  src/apis/StoreDetail/StoresProduct.ts
  src/apis/StoreDetail/StoresReview.ts
  src/components/DetailPopup/DetailPopup.tsx
  src/components/Navigationbar.tsx
  src/components/ReviewWrite/Addpic.tsx
  src/components/ReviewWrite/ReviewWrite.tsx
  src/components/ReviewWrite/StarRating.tsx
  src/components/ReviewWrite/Storetag.tsx
  src/components/ReviewWrite/Tagitem.tsx
  src/components/ReviewWrite/Text.tsx
  src/components/StoreDetail/DetailBox.tsx
  src/components/StoreDetail/Event.tsx
  src/components/StoreDetail/Eventlist.tsx
  src/components/StoreDetail/Linkbuttons.tsx
  src/components/StoreDetail/MyReview.tsx
  src/components/StoreDetail/Product.tsx
  src/components/StoreDetail/Productlist.tsx
  src/components/StoreDetail/Review.tsx
  src/components/StoreDetail/Reviewlist.tsx
  src/components/StoreDetail/Storename.tsx
  src/pages/Login/KakaoLoginHandeler.tsx
  src/pages/StoreDetail.tsx
  src/recoil/Reviewlist.ts
  src/recoil/StoreDetail/StoresState.ts
  src/recoil/StoreDetail/types.ts
  src/recoil/index.ts
Labels: new feature

#78 Feature/72 검색 페이지 api 연동
  src/apis/SearchApi.ts
  src/components/Search/PopularSearchList.tsx
  src/components/Search/RecentSearchList.tsx
  src/components/SearchFile/SearchResultList.tsx
  src/pages/Search.tsx
  src/recoil/index.ts
  src/recoil/searchToggleState.ts
  src/recoil/types.ts
Labels: new feature

#77 feat: 지도 페이지 마커, 이벤트 상세 모달 api 연동
  src/apis/Map/Markers.ts
  src/apis/StoreDetail/EventDetail.ts
  src/apis/customApi.ts
  src/components/EventDetail/EventDetail.tsx
  src/components/EventDetail/SlideBox.tsx
  src/components/Login/Loginbutton.tsx
  src/components/Map/MarkerInfo.tsx
  src/components/StoreDetail/Event.tsx
  src/pages/Map.tsx
  src/pages/StoreDetail.tsx
  src/recoil/StoreDetail/StoresState.ts
  src/recoil/StoreDetail/types.ts
Labels: new feature

#81 doc: yaml 파일 추가, readme 링크 수정
  .github/workflows/front-build.yaml
  README.md
Labels: documentation

#83 doc: yaml test
  .github/workflows/front-build.yaml
Labels: documentation

#89 Fix/88 검색 페이지 수정
  public/assets/Search/delete.png
  public/assets/Search/delete.svg
  public/assets/Search/search.png
  public/assets/Search/search.svg
  src/components/Search/PopularSearchList.tsx
  src/components/Search/RecentSearchList.tsx
  src/components/Search/SearchBar.tsx
  src/components/SearchFile/NoSearchFile.tsx
  src/pages/Search.tsx
  src/recoil/index.ts
  src/recoil/searchState.ts
Labels: fix

#91 Feature/73 홈화면 api 연동
  src/apis/Home/BookMarksApi.ts
  src/apis/Home/CurationsApi.ts
  src/apis/Home/MyApi.ts
  src/apis/Home/NearestApi.ts
  src/apis/Home/TodayApi.ts
  src/apis/Home/TrendApi.ts
  src/apis/Home/index.ts
  src/apis/SessionApi.ts
  src/components/Home/Ad/Slider/AdSlider.tsx
  src/components/Home/Ad/Slider/SliderItem.tsx
  src/components/Home/Items.tsx
  src/components/Home/Nearest.tsx
  src/components/Home/Slider/BaseSliderItem.tsx
  src/components/Home/Slider/CurationSliderItem.tsx
  src/components/Home/Slider/HomeSlider.tsx
  src/components/Home/StoreInfo.tsx
  src/components/Home/index.ts
  src/pages/Home.tsx
  src/recoil/Home/HomeState.ts
  src/recoil/Home/HomeStateType.ts
  src/recoil/session.ts
Labels: new feature

#87 Feature/79 닉네임설정 계정관리 api 연동
  src/apis/EditApi.ts
  src/components/Edit/EditButton.tsx
  src/components/Edit/KakaoEmail.tsx
  src/components/Edit/ProfileEdit.tsx
  src/components/Edit/ProfileImgModal.tsx
  src/pages/Setting.tsx
  src/recoil/editState.ts
  src/recoil/index.ts
Labels: new feature

#92 fix 수정사항 긴급수정
  src/apis/Event/Event.ts
  src/apis/Home/BookMarksApi.ts
  src/apis/SellingProduct/Products.ts
  src/apis/SessionApi.ts
  src/components/DetailPopup/DetailPopup.tsx
  src/components/EventEdit/DefaultList.tsx
  src/components/EventEdit/Product.tsx
  src/components/EventEdit/SlideBox.tsx
  src/components/EventEdit/TabContents.tsx
  src/components/EventEdit/index.ts
  src/components/ReviewWrite/ReviewWrite.tsx
  src/components/StoreDetail/MyReview.tsx
  src/pages/Evnentmanage.tsx
  src/recoil/Home/HomeState.ts
  src/recoil/session.ts
Labels: fix

#93 Feature/72 검색 페이지 api 연동
  package-lock.json
  package.json
  public/assets/Search/Staro.svg
  public/assets/Search/Starx.svg
  public/assets/Search/북마크o.svg
  public/assets/Search/북마크x.svg
  src/components/DetailPopup/DetailPopup.tsx
  src/components/SearchFile/SearchResultList.tsx
Labels: new feature

#94 Feature/86 점주 이벤트 관리 api 연결
  package-lock.json
  package.json
  src/apis/Event/Event.ts
  src/apis/SellingProduct/Products.ts
  src/apis/StoreDetail/Bookmark.ts
  src/apis/StoreDetail/Like.ts
  src/apis/StoreDetail/ReviewSend.ts
  src/apis/StoreDetail/StoresReview.ts
  src/components/DetailPopup/DetailPopup.tsx
  src/components/DetailPopup/SharePopup.tsx
  src/components/EventDetail/EventDetail.tsx
  src/components/EventDetail/SlideBox.tsx
  src/components/EventDetail/SlidePic.tsx
  src/components/EventEdit/Addonepic.tsx
  src/components/EventEdit/Addpic.tsx
  src/components/EventEdit/EventDate.tsx
  src/components/EventEdit/EventEdit.tsx
  src/components/EventEdit/EventExplane.tsx
  src/components/EventEdit/EventLink.tsx
  src/components/EventEdit/Eventname.tsx
  src/components/EventEdit/index.ts
  src/components/Home/Items.tsx
  src/components/Home/Nearest.tsx
  src/components/Home/Slider/BaseSliderItem.tsx
  src/components/Home/Slider/CurationSliderItem.tsx
  src/components/Home/Slider/HomeSlider.tsx
  src/components/Map/MarkerInfo.tsx
  src/components/Navigationbar.tsx
  src/components/ProductRegister/ProductRegistration.tsx
  src/components/ReviewWrite/ReviewWrite.tsx
  src/components/SellingProduct/SlidePic.tsx
  src/components/StoreDetail/DetailBox.tsx
  src/components/StoreDetail/Linkbuttons.tsx
  src/components/StoreDetail/Review.tsx
  src/components/StoreDetail/Reviewlist.tsx
  src/components/StoreDetail/SlideBox.tsx
  src/components/StoreDetail/SlidePic.tsx
  src/components/StoreDetail/Storename.tsx
  src/pages/Evnentmanage.tsx
  src/pages/Home.tsx
  src/pages/Setting.tsx
  src/recoil/StoreDetail/StoresState.ts
  src/recoil/StoreDetail/types.ts
  src/recoil/eventEdit.ts
  src/recoil/index.ts
  src/recoil/modals.ts
Labels: new feature

#95 Feature/90 내가 쓴 리뷰 페이지 api 연동
  src/apis/ReviewApi.ts
  src/pages/MyReview.tsx
Labels: new feature

#97 Fix/기타이슈수정
  src/App.tsx
  src/apis/ReviewApi.ts
  src/components/DetailPopup/DetailPopup.tsx
  src/components/Edit/AccountModal.tsx
  src/components/EventEdit/EventEdit.tsx
  src/components/ProductRegister/ProductRegistration.tsx
  src/components/ReviewWrite/ReviewWrite.tsx
  src/components/StoreDetail/Reviewlist.tsx
  src/pages/404Error.tsx
  src/pages/MyReview.tsx
  src/pages/NickName.tsx
  src/pages/Setting.tsx
Labels: fix

#99 feat : 사진 클릭시 외부링크로 이동
  src/components/Home/Slider/CurationSliderItem.tsx
Labels: fix

#100 Fix/기타이슈수정
  public/assets/StoreDetail/bookmark_o.svg
  src/App.tsx
  src/apis/Mypage/BookmarkPage.ts
  src/components/Home/Slider/CurationSliderItem.tsx
  src/components/Mypage/index.ts
  src/pages/MyBookmark.tsx
  src/pages/index.ts
  src/recoil/Mypage/bookmarkpage.ts
Labels: fix

#101 fix: 큐레이션 드래그시 클릭방지
  src/components/Home/Slider/CurationSliderItem.tsx
  src/components/Home/Slider/HomeSlider.tsx
Labels: fix

#105 Feature/71 점주신청 api 연동
  src/apis/Owner/OwnerApi.ts
  src/apis/customApi.ts
  src/components/Navigationbar.tsx
  src/components/Owner/InputField.tsx
  src/components/Owner/SearchAddress.tsx
  src/hooks/Owner/useInput.ts
  src/pages/Home.tsx
  src/pages/Owner.tsx
  src/recoil/Mypage/myPageState.ts
  src/recoil/Owner/owner.ts
  src/recoil/Owner/ownerState.ts
  src/recoil/Owner/ownerStateTypes.ts
  src/recoil/Owner/ownerTypes.ts
  src/recoil/index.ts
Labels: new feature

#106 fix: 홈화면 북마크 수정
  src/components/Home/Slider/HomeSlider.tsx
  src/components/Navigationbar.tsx
  src/components/Search/RecentSearchList.tsx
  src/pages/Map.tsx
  src/pages/MyBookmark.tsx
  src/pages/Search.tsx
  src/recoil/Mypage/bookmarkpage.ts
Labels: fix

#107 Feature/70 마이페이지 북마크 리뷰 api 연동
  src/App.tsx
  src/apis/Mypage/BookMarksApi.ts
  src/apis/Mypage/ManagerStoreApi.ts
  src/apis/Mypage/ReviewApi.ts
  src/apis/Mypage/index.ts
  src/components/Edit/EditButton.tsx
  src/components/Edit/KakaoEmail.tsx
  src/components/Modal/BookMarkModal.tsx
  src/components/Modal/ConfirmModal.tsx
  src/components/Modal/ReviewModal.tsx
  src/components/Mypage/BookMarkList.tsx
  src/components/Mypage/PersonalInfo.tsx
  src/components/Mypage/ReviewList.tsx
  src/pages/Mypage.tsx
  src/pages/OwnerMypage.tsx
  src/pages/index.ts
  src/recoil/Mypage/myPageState.ts
  src/recoil/Mypage/myPageStateType.ts
  src/recoil/confirmModal.ts
  src/recoil/editState.ts
Labels: new feature

#113 fix: 검색창 북마크 로직적용
  src/components/SearchFile/SearchResultList.tsx
Labels: fix

#115 fix: 오타 수정
  src/components/SearchFile/SearchResultList.tsx
Labels: fix

#116 fix: 이벤트 상세 페이지 하단 간격 수정
  src/components/EventDetail/EventDetail.tsx
Labels: fix

#117 fix: 개인정보처리방침
  src/pages/NickName.tsx
Labels: fix
